const actors = [
    {name: "Tom", surname: "Hanks"},
    {name: "Julia", surname: "Roberts"},
    {name: "George", surname: "Clooney"},
    {name: "Dustin", surname: "Hoffman"},
    {name: "Jessica", surname: "Chastain"},
    {name: "Zoe", surname: "Saldana"},
    {name: "Gary", surname: "Oldman"},
    {name: "Christopher", surname: "Walken"},
    {name: "Meryl", surname: "Streep"},
    {name: "Kate", surname: "Winslet"},
    {name: "Michael", surname: "Keaton"},
    {name: "Sigourney", surname: "Weaver"},
    {name: "Bruce", surname: "Willis"},
    {name: "Hugh", surname: "Grant"},
    {name: "Matt", surname: "Damon"},
    {name: "Emma", surname: "Stone"},
    {name: "Laura", surname: "Dern"},
    {name: "Jim", surname: "Carrey"},
    {name: "Christian", surname: "Bale"},
    {name: "Johnny", surname: "Depp"},
    {name: "Keanu", surname: "Reeves"},
    {name: "Audrey", surname: "Hepburn"},
    {name: "Robert", surname: "De Niro"},
    {name: "Reece", surname: "Witherspoon"},
    {name: "Jennifer", surname: "Lawrence"},
    {name: "Will", surname: "Smith"},
    {name: "Bill", surname: "Paxton"},
    {name: "Gene", surname: "Hackman"},
    {name: "Gwyneth", surname: "Paltrow"},
    {name: "Helen", surname: "Mirren"},
    {name: "Denzel", surname: "Washington"},

]

export {actors}