const actors = [
    {name: "Tom", surname: "Hanks", fullName: "Tom Hanks"},
    {name: "Julia", surname: "Roberts", fullName: "Julia Roberts"},
    {name: "George", surname: "Clooney", fullName: "George Clooney"},
    {name: "Dustin", surname: "Hoffman", fullName: "Dustin Hoffman"},
    {name: "Jessica", surname: "Chastain", fullName: "Jessica Chastain"},
    {name: "Zoe", surname: "Saldana", fullName: "Zoe Saldana"},
    {name: "Gary", surname: "Oldman", fullName: "Gary Oldman"},
    {name: "Christopher", surname: "Walken", fullName: "Christopher Walken"},
    {name: "Meryl", surname: "Streep", fullName: "Meryl Streep"},
    {name: "Kate", surname: "Winslet", fullName: "Kate Winslet"},
    {name: "Michael", surname: "Keaton", fullName: "Michael Keaton"},
    {name: "Sigourney", surname: "Weaver", fullName: "Sigourney Weaver"},
    {name: "Bruce", surname: "Willis", fullName: "Bruce Willis"},
    {name: "Hugh", surname: "Grant", fullName: "Hugh Grant"},
    {name: "Matt", surname: "Damon", fullName: "Matt Damon"},
    {name: "Emma", surname: "Stone", fullName: "Emma Stone"},
    {name: "Laura", surname: "Dern", fullName: "Laura Dern"},
    {name: "Jim", surname: "Carrey", fullName: "Jim Carrey"},
    {name: "Christian", surname: "Bale", fullName: "Christian Bale"},
    {name: "Johnny", surname: "Depp", fullName: "Johnny Depp"},
    {name: "Keanu", surname: "Reeves", fullName: "Keanu Reeves"},
    {name: "Robert", surname: "De Niro", fullName: "Robert De Niro"},
    {name: "Jennifer", surname: "Lawrence", fullName: "Jennifer Lawrence"},
    {name: "Will", surname: "Smith", fullName: "Will Smith"},
    {name: "Bill", surname: "Paxton", fullName: "Bill Paxton"},
    {name: "Gene", surname: "Hackman", fullName: "Gene Hackman"},
    {name: "Gwyneth", surname: "Paltrow", fullName: "Gwyneth Paltrow"},
    {name: "Helen", surname: "Mirren", fullName: "Helen Mirren"},
    {name: "Denzel", surname: "Washington", fullName: "Denzel Washington"},
    {name: "Brad", surname: "Pitt", fullName: "Brad Pitt"},
    {name: "Angelina", surname: "Jolie", fullName: "Angelina Jolie"},
    {name: "Robert", surname: "Redford", fullName: "Robert Redford"},
    {name: "Marlon", surname: "Brando", fullName: "Marlon Brando"},
    {name: "Paul", surname: "Newman", fullName: "Paul Newman"},
    {name: "Faye", surname: "Dunaway", fullName: "Faye Dunaway"},
    {name: "Charlize", surname: "Theron", fullName: "Faye Dunaway"},
    {name: "Tom", surname: "Hardy", fullName: "Tom Hardy"},
    {name: "Sharon", surname: "Stone", fullName: "Sharon Stone"},
    {name: "Michael", surname: "Douglas", fullName: "Michael Douglas"},

]

export {actors}